Script started on 2019-12-30 12:21:14+03:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="85" LINES="11"]
â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹[1K[1mscript[0m [[32menter[0m/[34mâ†‘[0m/[34mâ†“[0m/[31mctrl+c[0m]
Script started, file is typescript
â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹[1K[1mscript[0m [[32menter[0m/[34mâ†‘[0m/[34mâ†“[0m/[31mctrl+c[0m][31m
Aborted[0m
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;32mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m)[00m [K[?1h=[?2004h[1m[31mp[0m[39m[90msql[39m[1m[31mp[1m[31my[0m[39m[90mt[90mh[90mon3 manage.py shell[39m[21D[1m[31mp[1m[31my[1m[31mt[0m[39m[1m[31mt[1m[31mh[0m[39m[0m[32mp[0m[32my[0m[32mt[0m[32mh[32mo[32mn[32m3[39m[39m [39m[4mm[39m[4ma[39m[4mn[39m[4ma[39m[4mg[39m[4me[39m[4m.[39m[4mp[39m[4my[24m[39m [39ms[39mh[39me[39ml[39ml[90ml[39m[90ml[90me[90mh[90ms[39m[39m[4mm[24m[39m [39m [39m [39m [4mm[4ma[24m[24mm[24makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/models.py", line 2, in <module>
    from django.contrib.auth.models import  AbstractUSer, BaseUserManager
ImportError: cannot import name 'AbstractUSer' from 'django.contrib.auth.models' (/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/models.py)
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m)[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/sVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/models.py", line 29, in <module>
    class User(AbstractUSer):
NameError: name 'AbstractUSer' is not defined
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 61
    add_fieldsets = (( None, {
                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                              add_fieldsets = (( None, {
                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 61
    add_fieldsets = ( None, {
                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()lf.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 61
    add_fieldsets = (None, {
                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 61
    add_fieldsets=(None, {
                 ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 61
    add_fieldsets=(None, {
                 ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[?1l>[?2004l
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 66
    )
    ^
IndentationError: unexpected indent
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 62
    add_fieldsets=(None, {"classes": ("Wide",), "fields": ("email","password1","password2"), },), )
                                                                                                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 62
    add_fieldsets=(None, {"classes": ("Wide",), "fields": ("email","password1","password2"), },), ),
                                                                                                  ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  Fi.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gg/Dev/federico/main/admin.py", line 62
    add_fieldsets=(None, {"classes": ("Wide",), "fields": ("email","password1","password2"), },),)
                                                                                                 ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m makemigrations[?1l>[?2004l
]2;python3 manage.py makemigrations]1;python3[36;1mMigrations for 'main':[0m
  [1mmain/migrations/0001_initial.py[0m
    - Create model Product
    - Create model ProductTag
    - Create model ProductImage
    - Add field tags to product
    - Create model User
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;32mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[0m[27m[24m[J[01;32mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [0m[27m[24m[J[01;32mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [1m[31mp[0m[39m[90mython3 manage.py makemigrations[39m[31D[1m[31mp[1m[31my[0m[39m[1m[31mp[1m[31my[1m[31mt[0m[39m[1m[31mt[1m[31mh[0m[39m[1m[31mh[1m[31mo[0m[39m[0m[32mp[0m[32my[0m[32mt[0m[32mh[0m[32mo[32mn[39m[32mn[32m3[39m[39m [39m[4mm[24m[4mm[39m[4ma[24m[4ma[39m[4mn[24m[4mn[39m[4ma[24m[4ma[39m[4mg[24m[4mg[39m[4me[24m[4me[39m[4m.[24m[4m.[39m[4mp[24m[4mp[39m[4my[24m[39m [39m[4mm[24m[24mm[39mi[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [12Dgrate[?1l>[?2004l
]2;python3 manage.py migrate]1;python3[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, main, sessions
[36;1mRunning migrations:[0m
  Applying contenttypes.0001_initial...[32;1m OK[0m
  Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
  Applying auth.0001_initial...[32;1m OK[0m
  Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
  Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
  Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
  Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
  Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
  Applying auth.0007_alter_validators_add_error_messages...[32;1m OK[0m
  Applying auth.0008_alter_user_username_max_length...[32;1m OK[0m
  Applying auth.0009_alter_user_last_name_max_length...[32;1m OK[0m
  Applying auth.0010_alter_group_name_max_length...[32;1m OK[0m
  Applying auth.0011_update_proxy_permissions...[32;1m OK[0m
  Applying main.0001_initial...[32;1m OK[0m
  Applying admin.0001_initial...[32;1m OK[0m
  Applying admin.0002_logentry_remove_auto_add...[32;1m OK[0m
  Applying admin.0003_logentry_add_action_flag_choices...[32;1m OK[0m
  Applying sessions.0001_initial...[32;1m OK[0m
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;32mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[1m[31mp[0m[39m[90mython3 manage.py migrate[39m[24D[1m[31mp[1m[31my[0m[39m[1m[31mp[1m[31my[1m[31mt[0m[39m[1m[31mt[1m[31mh[0m[39m[0m[32mp[0m[32my[0m[32mt[0m[32mh[32mo[32mn[32m3[39m[39m [39m[4mm[39m[4ma[39m[4mn[39m[4ma[39m[4mg[39m[4me[39m[4m.[39m[4mp[39m[4my[24m[39m [39mm[39mi[39mg[39mr[39ma[39mt[39me[90me[39m[90mt[90ma[90mr[90mg[39m[4mm[24m[90mi[24m[90mm[39m[39mc[39m [39m [39m [39m [39m [39m reatesuperuser[?1l>[?2004l
]2;python3 manage.py createsuperuser]1;python3Email address: labankiplagat81@gmail.com
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
AttributeError: 'UserManager' object has no attribute 'create_superuser'
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m createsuperuser[?1l>[?2004l
]2;python3 manage.py createsuperuser]1;python3Email address: labank   ohkiplagat81
[31;1mError: Enter a valid email address.
[0mEmail address: labohkip81\2  @gmail.com
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/home/gg/Dev/federico/main/models.py", line 27, in create_superuser
    raise ValueError(" Superuser must have is_staff=True.")
ValueError:  Superuser must have is_staff=True.
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[32mpython3[39m [4mmanage.py[24m createsuperuser[?1l>[?2004l
]2;python3 manage.py createsuperuser]1;python3Email address: labankiplagay t1 81@gmsil   ail.com
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/gg/.local/share/virtualenvs/federico-ZEnVEkPT/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/home/gg/Dev/federico/main/models.py", line 27, in create_superuser
    raise ValueError(" Superuser must have is_staff=True.")
ValueError:  Superuser must have is_staff=True.
[1m[7m%[27m[1m[0m                                                                                     ]2;gg@gg-Latitude-5490: ~/Dev/federico]1;~/Dev/federico[0m[27m[24m[J[01;31mâžœ  [36mfederico[00m [01;34mgit:([31mmaster[34m) [33mâœ—[00m [K[?1h=[?2004h[3